"""
backend/agents/ — All agent node functions for the LangGraph workflow.
Each agent receives the graph state dict and returns an updated state dict.
"""

import json
import os
import re
from typing import Dict, Any

from backend.utils.llm import run_llm, get_client, MODEL
from backend.utils.prompts import (
    SUPERVISOR_PROMPT,
    POLICY_AGENT_PROMPT,
    BILLING_AGENT_PROMPT,
    CLAIMS_AGENT_PROMPT,
    GENERAL_HELP_PROMPT,
    HUMAN_ESCALATION_PROMPT,
    FINAL_ANSWER_PROMPT,
)
from backend.db.database import (
    get_policy_details,
    get_auto_policy_details,
    get_billing_info,
    get_payment_history,
    get_claim_status,
    ask_user,
    
)
from backend.db.vector_store import search_faqs
from backend.utils.tracing import trace_agent


def clean_llm_output(text: str) -> str:
    """Removes <think> tags generated by reasoning models to prevent context bleed."""
    if not isinstance(text, str):
        return text
    return re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()

# ─── Supervisor ─────────────────────────────────────────────────────────────

@trace_agent
def supervisor_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Routes the conversation to the appropriate specialist agent.
    Asks the user for clarification if essential info is missing.
    Enforces a max-iteration guard to prevent infinite loops.
    """
    n_iter = state.get("n_iteration", 0) + 1
     
    print(f"🔍 Supervisor called with n_iter: {state.get('n_iteration', 0)}")
    print(f"📝 Conversation history: {state.get('conversation_history', '')}")
    # Guard: escalate after 3 supervisor loops
    if n_iter >= 8:
        print("⚠️ Max iterations reached in supervisor. Escalating to human.")
        updated_history = (
            state.get("conversation_history", "")
            + "\nAssistant: This issue requires human review. Escalating to a support specialist."
        )
        return {
            "escalate_to_human": True,
            "conversation_history": updated_history,
            "next_agent": "human_escalation_agent",
            "n_iteration": n_iter,
        }

    conversation_history = state.get("conversation_history", "")
    prompt = SUPERVISOR_PROMPT.format(conversation_history=conversation_history)

    ask_user_tool = [
        {
            "type": "function",
            "function": {
                "name": "ask_user",
                "description": "Ask the user for essential missing info (policy number, customer ID, claim ID).",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "question": {"type": "string", "description": "Short question to ask the user"},
                        "missing_info": {"type": "string", "description": "What info is missing"},
                    },
                    "required": ["question", "missing_info"],
                },
            },
        }
    ]

    client = get_client()
    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "system", "content": prompt}],
        tools=ask_user_tool,
        tool_choice="auto",
    )
    message = response.choices[0].message

    # If supervisor wants to ask user something, surface the question
    if getattr(message, "tool_calls", None):
        for tc in message.tool_calls:
            if tc.function.name == "ask_user":
                print("🗣️ Supervisor is asking the user for clarification.")
                try:
                    arguments = tc.function.arguments or "{}"
                    args = json.loads(arguments)

                    if not isinstance(args, dict):
                        args = {}
                    print(f"📋 Parsed tool arguments: {args}")
                except (json.JSONDecodeError, TypeError, AttributeError) as e:
                    print(f"⚠️ Malformed tool JSON caught ({e}). Falling back to default.")
                    args = {}
                 
                question = args.get("question", "Could you provide more details so I can assist you?")
                print(f"❓ Supervisor question: {question}")
                updated_history = state.get("conversation_history", "") + f"\nAssistant: {question}"
                # Signal to the API layer that user input is needed
                return {
                    "needs_clarification": True,
                    "clarification_question": question,
                    "n_iteration": n_iter,
                    "conversation_history": updated_history,
                    "messages": state.get("messages", []),
                    "next_agent": None,
                    "end_conversation": False,
                }
                


     
    # if getattr(message, "tool_calls", None):
    #     print("🛠️ Supervisor requesting user clarification")
    #     for tool_call in message.tool_calls:
    #         if tool_call.function.name == "ask_user":
    #             args = json.loads(tool_call.function.arguments)
                
    #             question = args.get("question", "Can you please provide more details?")
    #             missing_info = args.get("missing_info", "additional information")
                
    #             print(f"❓ Asking user: {question}")
             
                
    #             # user_response_data = ask_user(question, missing_info)
    #             # user_response = user_response_data["context"]
                
    #             # print(f"✅ User response: {user_response}")
                
    #             # Update conversation history with the question
    #             updated_history = conversation_history + f"\nAssistant: {question}"
    #             # updated_history = updated_history + f"\nUser: {user_response}"
                
    #             return {
    #                 "needs_clarification": True,
    #                 "clarification_question": question,
    #                 "n_iteration": n_iter,
    #                 "conversation_history": updated_history
    #             }

    
    # Parse routing decision
    try:
        content = clean_llm_output(message.content or "{}")
        parsed = json.loads(content)
    except (json.JSONDecodeError, TypeError):
        parsed = {}

    next_agent = parsed.get("next_agent", "general_help_agent")
    task = parsed.get("task", "Assist the user with their query.")
    justification = parsed.get("justification", "")

    updated_history = (
        conversation_history + f"\nAssistant: Routing to {next_agent} for: {task}"
    )
    print(f"➡️ Routing to {next_agent} with task: {task} (justification: {justification})") 
    return {
        "next_agent": next_agent,
        "task": task,
        "justification": justification,
        "conversation_history": updated_history,
        "n_iteration": n_iter,
        "needs_clarification": False,
        "end_conversation": False,
        "messages": state.get("messages", []),
    }
  
# ─── Policy Agent ────────────────────────────────────────────────────────────

@trace_agent
def policy_agent_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """Handles policy details, coverage, and auto policy information."""
    prompt = POLICY_AGENT_PROMPT.format(
        task=state.get("task", ""),
        policy_number=state.get("policy_number", "Not provided"),
        customer_id=state.get("customer_id", "Not provided"),
        conversation_history=state.get("conversation_history", ""),
    )
    tools = [
        {"type": "function", "function": {
            "name": "get_policy_details",
            "description": "Fetch policy info by policy number",
            "parameters": {"type": "object", "properties": {"policy_number": {"type": "string"}}},
        }},
        {"type": "function", "function": {
            "name": "get_auto_policy_details",
            "description": "Get auto policy details including vehicle info",
            "parameters": {"type": "object", "properties": {"policy_number": {"type": "string"}}},
        }},
    ]


    raw_result = run_llm(prompt, tools, {"get_policy_details": get_policy_details, "get_auto_policy_details": get_auto_policy_details})
    result = clean_llm_output(raw_result)
    return {
        "messages": [*state.get("messages", []), {"role": "assistant", "content": result}],
        "conversation_history": state.get("conversation_history", "") + f"\nPolicy Agent: {result}",
        # "end_conversation": True
    }


# ─── Billing Agent ───────────────────────────────────────────────────────────

@trace_agent
def billing_agent_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """Handles billing statements, payment history, and premium queries."""
    prompt = BILLING_AGENT_PROMPT.format(
        task=state.get("task", ""),
        conversation_history=state.get("conversation_history", ""),
    )
    tools = [
        {"type": "function", "function": {
            "name": "get_billing_info",
            "description": "Retrieve billing information",
            "parameters": {"type": "object", "properties": {
                "policy_number": {"type": "string"},
                "customer_id": {"type": "string"},
            }},
        }},
        {"type": "function", "function": {
            "name": "get_payment_history",
            "description": "Fetch recent payment history",
            "parameters": {"type": "object", "properties": {"policy_number": {"type": "string"}}},
        }},
    ]

    raw_result = run_llm(prompt, tools, {"get_billing_info": get_billing_info, "get_payment_history": get_payment_history})
    result = clean_llm_output(raw_result)
    return {
        "messages": [*state.get("messages", []), {"role": "assistant", "content": result}],
        "conversation_history": state.get("conversation_history", "") + f"\nBilling Agent: {result}",
        # "end_conversation": True
    }


# ─── Claims Agent ────────────────────────────────────────────────────────────

@trace_agent
def claims_agent_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """Handles claim status lookups and claim-related queries."""
    prompt = CLAIMS_AGENT_PROMPT.format(
        task=state.get("task", ""),
        policy_number=state.get("policy_number", "Not provided"),
        claim_id=state.get("claim_id", "Not provided"),
        conversation_history=state.get("conversation_history", ""),
    )
    tools = [
        {"type": "function", "function": {
            "name": "get_claim_status",
            "description": "Retrieve claim details by claim ID or policy number",
            "parameters": {"type": "object", "properties": {
                "claim_id": {"type": "string"},
                "policy_number": {"type": "string"},
            }},
        }},
    ]
    raw_result = run_llm(prompt, tools, {"get_claim_status": get_claim_status})
    result = clean_llm_output(raw_result)
    return {
        "messages": [*state.get("messages", []), {"role": "assistant", "content": result}],
        "conversation_history": state.get("conversation_history", "") + f"\nClaims Agent: {result}",
        # "end_conversation": True
    }


# ─── General Help Agent ──────────────────────────────────────────────────────

@trace_agent
def general_help_agent_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """Answers general insurance FAQs using ChromaDB retrieval (RAG)."""
    user_query = state.get("user_input", "")
    faqs = search_faqs(user_query, n_results=3)

    faq_context = ""
    if faqs:
        for i, faq in enumerate(faqs):
            faq_context += f"FAQ {i+1} (score: {faq['score']:.3f})\nQ: {faq['question']}\nA: {faq['answer']}\n\n"
    else:
        faq_context = "No relevant FAQs were found."

    prompt = GENERAL_HELP_PROMPT.format(
        task=state.get("task", "General insurance support"),
        conversation_history=state.get("conversation_history", ""),
        faq_context=faq_context,
    )
    raw_result = run_llm(prompt)
    result = clean_llm_output(raw_result)
    return {
        "messages": [*state.get("messages", []), {"role": "assistant", "content": result}],
        "conversation_history": state.get("conversation_history", "") + f"\nGeneral Help Agent: {result}",
        # "end_conversation": True
    }


# ─── Human Escalation Agent ──────────────────────────────────────────────────

@trace_agent
def human_escalation_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """Gracefully escalates the conversation to a human agent."""
    prompt = HUMAN_ESCALATION_PROMPT.format(
        task=state.get("task", ""),
        conversation_history=state.get("conversation_history", ""),
    )
    client = get_client()
    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "system", "content": prompt}],
    )
    raw_answer = response.choices[0].message.content
    answer = clean_llm_output(raw_answer)

    return {
        "final_answer": answer,
        "requires_human_escalation": True,
        "messages": [*state.get("messages", []), {"role": "assistant", "content": answer}],
        "end_conversation": True
    }


# ─── Final Answer Agent ──────────────────────────────────────────────────────

@trace_agent
def final_answer_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """Generates a clean, user-friendly final answer from the specialist response."""
    print("🎯 Final Answer Agent compiling the final response for the user.")
    # user_query = state.get("user_input", "")
    # messages = state.get("messages", [])

    # # Get the most recent assistant message
    # specialist_response = "No response available."
    # for msg in reversed(messages):
    #     content = msg.get("content", "") if isinstance(msg, dict) else getattr(msg, "content", "")
    #     if content and "clarification" not in content.lower():
    #         specialist_response = content
    #         break
    conversation_history = state.get("conversation_history", "No history available.")
    # prompt = FINAL_ANSWER_PROMPT.format(
    #     user_query=user_query,
    #     specialist_response=specialist_response,
    # )

    prompt = FINAL_ANSWER_PROMPT.format(
        conversation_history=conversation_history
    )
    client = get_client()
    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "system", "content": prompt}],
    )
    raw_final_answer = response.choices[0].message.content
    final_answer = clean_llm_output(raw_final_answer)

    return {
        "final_answer": final_answer,
        "end_conversation": True,
        "conversation_history": state.get("conversation_history", "") + f"\nFinal Answer Agent: {final_answer}",
        "messages": [{"role": "assistant", "content": final_answer}],
    }
